// Automatically generated by MockGen. DO NOT EDIT!
// Source: scraper/fetcher (interfaces: RSS,RSSChannel)

package mock_fetcher

import (
	gomock "github.com/golang/mock/gomock"
	fetcher "scraper/fetcher"
)

// Mock of RSS interface
type MockRSS struct {
	ctrl     *gomock.Controller
	recorder *_MockRSSRecorder
}

// Recorder for MockRSS (not exported)
type _MockRSSRecorder struct {
	mock *MockRSS
}

func NewMockRSS(ctrl *gomock.Controller) *MockRSS {
	mock := &MockRSS{ctrl: ctrl}
	mock.recorder = &_MockRSSRecorder{mock}
	return mock
}

func (_m *MockRSS) EXPECT() *_MockRSSRecorder {
	return _m.recorder
}

func (_m *MockRSS) GetChannel() fetcher.RSSChannel {
	ret := _m.ctrl.Call(_m, "GetChannel")
	ret0, _ := ret[0].(fetcher.RSSChannel)
	return ret0
}

func (_mr *_MockRSSRecorder) GetChannel() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetChannel")
}

func (_m *MockRSS) GetLink() string {
	ret := _m.ctrl.Call(_m, "GetLink")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockRSSRecorder) GetLink() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetLink")
}

// Mock of RSSChannel interface
type MockRSSChannel struct {
	ctrl     *gomock.Controller
	recorder *_MockRSSChannelRecorder
}

// Recorder for MockRSSChannel (not exported)
type _MockRSSChannelRecorder struct {
	mock *MockRSSChannel
}

func NewMockRSSChannel(ctrl *gomock.Controller) *MockRSSChannel {
	mock := &MockRSSChannel{ctrl: ctrl}
	mock.recorder = &_MockRSSChannelRecorder{mock}
	return mock
}

func (_m *MockRSSChannel) EXPECT() *_MockRSSChannelRecorder {
	return _m.recorder
}

func (_m *MockRSSChannel) GetArticle(_param0 int) fetcher.Article {
	ret := _m.ctrl.Call(_m, "GetArticle", _param0)
	ret0, _ := ret[0].(fetcher.Article)
	return ret0
}

func (_mr *_MockRSSChannelRecorder) GetArticle(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetArticle", arg0)
}

func (_m *MockRSSChannel) GetNumArticles() int {
	ret := _m.ctrl.Call(_m, "GetNumArticles")
	ret0, _ := ret[0].(int)
	return ret0
}

func (_mr *_MockRSSChannelRecorder) GetNumArticles() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetNumArticles")
}
